USE SGEI
GO

--SELECT * FROM CLIENTES

SELECT * FROM CLIENTES
SELECT * FROM PRODUTOS

SELECT
A.ID_CLIENTE,
A.NOME,
A.PAIS,
B.PESO,
B.VALORUNITARIO,

-- OPERADOR DE MULTIPLICACÃO
B.VALORUNITARIO * A.ID_CLIENTE AS VALOR_TOTAL_CLIENTE,

-- OPERADOR DE DIVISAO
B.VALORUNITARIO / A.ID_CLIENTE AS VALOR_DIVIDIDO_CLIENTE,

-- PERCENTUAL
B.VALORUNITARIO / 100  AS PERCENTUAL,

--ADIÇAO
B.VALORUNITARIO + (15 * A.ID_CLIENTE) AS VALOR_ADICAO_CLIENTE,

--SUBTRAÇÃO
B.VALORUNITARIO - (15 * A.ID_CLIENTE) AS VALOR_SUBTRACAO_CLIENTE


FROM CLIENTES A(NOLOCK)
LEFT JOIN PRODUTOS B(NOLOCK) ON (B.ID_PRODUTO = A.ID_CLIENTE)
