-- CONSULTAR DADOS UTILIZADO INNER JOIN
--

USE SGEI

SELECT * FROM CLIENTES
SELECT * FROM PRODUTOS
SELECT * FROM EXPORTACOES
SELECT * FROM IMPORTACOES


SELECT
*   -- lISTARÁ TODAS AS INFORMAÇÕES
FROM CLIENTES A(NOLOCK)
INNER JOIN EXPORTACOES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)

SELECT
*   -- lISTARÁ TODAS AS INFORMAÇÕES
FROM CLIENTES A(NOLOCK)
INNER JOIN IMPORTACOES C(NOLOCK) ON (C.ID_CLIENTE = A.ID_CLIENTE)


-- AS LETRAS A, B, C SÃO ILHAS 'APELIDOS' PARA TABELAS (PODES ESCOLHER QLQR NOME)
-- PARA RELACIONAR AS TABELAS, DEVE HAVER UM CAMPO COMUM ENTRE AS DUAS *EX: ID_CLIENTE


--OBTENDO SÓ OS CAMPOS NECESSÁRIOS

SELECT
A.ID_CLIENTE,
A.NOME,
A.PAIS,
B.PORTO_DESTINO,
B.SITUACAO
FROM CLIENTES A(NOLOCK)
INNER JOIN EXPORTACOES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
ORDER BY A.NOME --ORDENANDO A CONSULTA



SELECT
A.ID_CLIENTE,
A.NOME,
A.PAIS,
B.PORTO_DESTINO,
B.SITUACAO
FROM CLIENTES A(NOLOCK)
INNER JOIN EXPORTACOES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
WHERE A.PAIS = 'Brasil' AND B.SITUACAO = 'CONCLUÍDO' -- SELECIONAR UMA OU MAIS CONDIÇÕES
ORDER BY A.NOME --ORDENANDO A CONSULTA


--LEFT JOIN

SELECT
A.ID_CLIENTE,
A.NOME,
A.PAIS,
B.PORTO_DESTINO,
B.SITUACAO
FROM CLIENTES A(NOLOCK)
LEFT JOIN EXPORTACOES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
--WHERE A.PAIS = 'Brasil' AND B.SITUACAO = 'CONCLUÍDO' -- SELECIONAR UMA OU MAIS CONDIÇÕES
ORDER BY A.NOME --ORDENANDO A CONSULTA


-- RIGHT JOIN

SELECT
A.ID_CLIENTE,
A.NOME,
A.PAIS,
B.PORTO_DESTINO,
B.SITUACAO
FROM CLIENTES A(NOLOCK)
RIGHT JOIN EXPORTACOES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
--WHERE A.PAIS = 'Brasil' AND B.SITUACAO = 'CONCLUÍDO' -- SELECIONAR UMA OU MAIS CONDIÇÕES
ORDER BY A.NOME --ORDENANDO A CONSULTA