-- SELECT SIMPLES DOS NOSSOS CLIENTES

SELECT * FROM CLIENTES

SELECT
A.ID_CLIENTE,
A.NOME,
A.CNPJ_CPF
FROM CLIENTES A(NOLOCK)

--UTILIZAR UM SUB SELECT

SELECT
A.ID_CLIENTE,
A.NOME,
A.CNPJ_CPF,
(SELECT COUNT(*) FROM EXPORTACOES B(NOLOCK) WHERE B.ID_CLIENTE = A.ID_CLIENTE) AS QTD_EXPORTACAO
FROM CLIENTES A(NOLOCK)

-- SE FOR NECESSÁRIO UTILIZAR MAIS DE UM SUB SELECT É MELHOR UTILIZAR INNER JOIN
--INNER JOIN É MELHOR USAR DO QUE SUB SELECT PARA PERFOMACE DO BANCO DE DADOS

SELECT
A.ID_CLIENTE,
A.NOME,
A.PAIS,
B.PORTO_DESTINO,
B.SITUACAO
FROM CLIENTES A(NOLOCK)
INNER JOIN EXPORTACOES B(NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)