-- RELEMBRANDO O QUE TEMOS NA TABELA DE PEDIDOS

USE SGEI
GO

SELECT * FROM PRODUTOS
GO

--SUM = SOMA
SELECT SUM(VALORUNITARIO) AS SOMA FROM PRODUTOS 


--AVG = AVERAGE = MEDIA
SELECT AVG(VALORUNITARIO) AS AVERAGE FROM PRODUTOS

--MIN = MINIMO
SELECT MIN(VALORUNITARIO) AS MINIMO FROM PRODUTOS

--MAX = MAXIMO
SELECT MAX(VALORUNITARIO) AS MAXIMO FROM PRODUTOS

--% = REPRESENTAR O MODULO DE DIVISAO 
SELECT
ID_PRODUTO,
VALORUNITARIO,
VALORUNITARIO % 2 AS MODULOS
FROM PRODUTOS

--SQRT = RAIZ QUADRADA
SELECT
ID_PRODUTO,
VALORUNITARIO,
SQRT (VALORUNITARIO) AS RAIZ_QUADRADA
FROM PRODUTOS

-- GROUP BY
--SELECT * FROM PRODUTOS
--SELECT * FROM CLIENTES


SELECT 
    C.Nome, --AS Cliente,
    SUM(I.Quantidade) AS TotalProdutosExportados
FROM ItensExportacao I
INNER JOIN Exportacoes E ON I.Id_Exportacao = E.Id_Exportacao
INNER JOIN Clientes C ON E.Id_Cliente = C.Id_Cliente
GROUP BY C.Nome;