--LEMBRE-SE DO EXEMPLO  DE UPDATE SIMPLES...

USE SGEI
GO


UPDATE PRODUTOS SET DESCRICAO = 'Notebook HP' WHERE ID_PRODUTO = 1
UPDATE PRODUTOS SET DESCRICAO = 'Televisão SAMSUNG 55"' WHERE ID_PRODUTO = 5
GO

SELECT * FROM PRODUTOS


-- UPDATE COM INNER JOIN
-- EU UTILIZEI O LEFT PORQUE MEU BANCO DE DADOS É DIFERENTE DO BANCO DO CURSO.

SELECT * FROM CLIENTES
SELECT * FROM EXPORTACOES
SELECT * FROM IMPORTACOES


SELECT * FROM CLIENTES A --CONSULTA LEFT JOIN
LEFT JOIN EXPORTACOES B (NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
LEFT JOIN IMPORTACOES C (NOLOCK) ON (C.ID_CLIENTE = A.ID_CLIENTE)
WHERE A.PAIS = 'BRASIL'
AND B.TIPO = 'EXP'



UPDATE A SET PAIS = 'BRAZIL' -- UPDATE LEFT JOIN
FROM CLIENTES A --***
LEFT JOIN EXPORTACOES B (NOLOCK) ON (B.ID_CLIENTE = A.ID_CLIENTE)
LEFT JOIN IMPORTACOES C (NOLOCK) ON (C.ID_CLIENTE = A.ID_CLIENTE)
WHERE A.PAIS = 'BRASIL'
AND B.TIPO = 'EXP'
