--INSERIR REGISTRO NAS TABELAS CLIENTES

USE SGEI

SELECT * FROM IMPORTACOES

INSERT INTO CLIENTES (NOME, CNPJ_CPF, PAIS) VALUES ('COMEX BRASIL LTDA', '12.345.678/0001-90', 'BRASIL');
INSERT INTO CLIENTES (NOME, CNPJ_CPF, PAIS) VALUES ('Global Trade S.A.', '98.765.432/0001-12', 'Brasil');
INSERT INTO CLIENTES (NOME, CNPJ_CPF, PAIS) VALUES ('Exporta Fácil ME', '11.222.333/0001-44', 'Brasil');
INSERT INTO CLIENTES (NOME, CNPJ_CPF, PAIS) VALUES ('Ocean Logistics', '55.666.777/0001-88', 'Estados Unidos');
INSERT INTO CLIENTES (NOME, CNPJ_CPF, PAIS) VALUES ('Porto Seguro Imports', '99.888.777/0001-66', 'China');

--INSERIR REGISTRO NAS TABELAS PRODUTOS

INSERT INTO PRODUTOS (DESCRICAO, CATEGORIA, PESO, VALORUNITARIO) VALUES ('Notebook Dell Inspiron', 'Eletrônicos', '2.5', '3500.00');
INSERT INTO PRODUTOS (DESCRICAO, CATEGORIA, PESO, VALORUNITARIO) VALUES ('Caixa de Café 1kg', 'Alimentos', '1.0', '45.90');
INSERT INTO PRODUTOS (DESCRICAO, CATEGORIA, PESO, VALORUNITARIO) VALUES ('Celular Samsung Galaxy', 'Eletrônicos', '0.4', '2200.00');
INSERT INTO PRODUTOS (DESCRICAO, CATEGORIA, PESO, VALORUNITARIO) VALUES ('Tênis Nike Air', 'Vestuário', '0.8', '499.99');
INSERT INTO PRODUTOS (DESCRICAO, CATEGORIA, PESO, VALORUNITARIO) VALUES ('Televisão LG 55"', 'Eletrônicos', '12.0', '3200.00');

--INSERIR REGISTRO NAS TABELAS EXPORTACOES

INSERT INTO EXPORTACOES (ID_CLIENTE, DATA_EXPORTACAO, PORTO_DESTINO, SITUACAO) VALUES (1, '2025-09-01', 'Porto de Roterdã', 'Concluido');
INSERT INTO EXPORTACOES (ID_CLIENTE, DATA_EXPORTACAO, PORTO_DESTINO, SITUACAO) VALUES (2, '2025-09-05', 'Porto de Hamburgo', 'Em andamento');
INSERT INTO EXPORTACOES (ID_CLIENTE, DATA_EXPORTACAO, PORTO_DESTINO, SITUACAO) VALUES (3, '2025-09-10', 'Porto de Antuérpia', 'Cancelado');

--INSERIR REGISTRO NAS TABELAS ITENSEXPORTACAO

INSERT INTO ITENSEXPORTACAO (ID_EXPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (1, 1, 50);   -- 50 notebooks Dell na exportação 1
INSERT INTO ITENSEXPORTACAO (ID_EXPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (1, 2, 200);  -- 200 caixas de café na exportação 1
INSERT INTO ITENSEXPORTACAO (ID_EXPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (2, 3, 100);  -- 100 celulares Samsung na exportação 2
INSERT INTO ITENSEXPORTACAO (ID_EXPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (2, 4, 300);  -- 300 tênis Nike na exportação 2
INSERT INTO ITENSEXPORTACAO (ID_EXPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (3, 5, 20);   -- 20 TVs LG na exportação 3

--INSERIR REGISTRO NAS TABELAS IMPORTACOES

INSERT INTO IMPORTACOES (ID_CLIENTE, DATA_IMPORTACAO, PORTO_ORIGEM, SITUACAO)VALUES (4, '2025-08-15', 'Porto de Xangai', 'Concluido');
INSERT INTO IMPORTACOES (ID_CLIENTE, DATA_IMPORTACAO, PORTO_ORIGEM, SITUACAO)VALUES (5, '2025-09-02', 'Porto de Miami', 'Em andamento');
INSERT INTO IMPORTACOES (ID_CLIENTE, DATA_IMPORTACAO, PORTO_ORIGEM, SITUACAO)VALUES	(5,	'2025-10-19', 'Porto de Londre', 'Em andamento');

--INSERIR REGISTRO NAS TABELAS ITENSIMPORTACAO

INSERT INTO ITENSIMPORTACAO (ID_IMPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (1, 2, 500);  -- 500 caixas de café
INSERT INTO ITENSIMPORTACAO (ID_IMPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (1, 5, 30);   -- 30 TVs LG 55"
INSERT INTO ITENSIMPORTACAO (ID_IMPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (2, 4, 200);  -- 200 tênis Nike Air
INSERT INTO ITENSIMPORTACAO (ID_IMPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (2, 1, 40);   -- 40 notebooks Dell Inspiron
INSERT INTO ITENSIMPORTACAO (ID_IMPORTACAO, ID_PRODUTO, QUANTIDADE)VALUES (3, 5, 20);   -- 20 TVs LG

SELECT * FROM ITENSIMPORTACAO