USE SGEI
GO

IF EXISTS (SELECT * FROM SYS.objects WHERE NAME = 'CLIENTES' AND type ='U')
	BEGIN
		DROP TABLE CLIENTES
	END
GO

CREATE TABLE CLIENTES(
ID_CLIENTE		INTEGER IDENTITY(1,1) PRIMARY KEY, -- IDENTITY(1,1) = GERAR UMA NUMERAÇÃO AUTOMATICA DE 1 EM 1.
NOME			VARCHAR(200),
CNPJ_CPF		VARCHAR(20),
PAÍS			VARCHAR(50))
GO

CREATE INDEX IDX_ID_CLIENTES ON CLIENTES(ID_CLIENTE) -- 1 NOME, 2 TABELA E 3 CAMPO
GO




IF EXISTS (SELECT * FROM SYS.objects WHERE NAME = 'PRODUTOS' AND type ='U')
	BEGIN
		DROP TABLE PRODUTOS
	END
GO

CREATE TABLE PRODUTOS(
ID_PRODUTO		INTEGER IDENTITY (1,1) PRIMARY KEY, -- Chave primária, autoincremento
DESCRICAO		VARCHAR(150), -- Nome/descrição do produto -- Até 150 caracteres (aceita acentos)
CATEGORIA		VARCHAR(50), -- Ex: "Eletrônicos", "Alimentos"  -- Até 50 caracteres
PESO			DECIMAL(10,2), -- Ex: 12345.67 kg  -- 10 dígitos no total, 2 após vírgula
VALORUNITARIO	DECIMAL(12,2)) -- Ex: 9999999999.99 -- 12 dígitos no total, 2 após vírgula
GO

CREATE INDEX IDX_ID_PRODUTOS ON PRODUTOS(ID_PRODUTO)
GO




IF EXISTS (SELECT * FROM SYS.objects WHERE NAME = 'EXPORTRACOES' AND type ='U')
	BEGIN
		DROP TABLE EXPORTRACOES
	END
GO

CREATE TABLE EXPORTACOES(
ID_EXPORTACAO	INTEGER IDENTITY (1,1) PRIMARY KEY,		-- chave primária, autoincremento
ID_CLIENTE		INTEGER FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),	-- FK que liga com a tabela Clientes
DATA_EXPORTACAO	DATE,	-- Data da exportação (sem hora) -- Se precisar registrar hora, pode usar DATETIME2
PORTO_DESTINO	VARCHAR(100),	-- Nome do porto de destino  -- Até 100 caracteres (ex: "Porto de Roterdã")
SITUACAO		VARCHAR(20)) -- texto livre (ex.: 'Em andamento', 'Concluido')
GO

CREATE INDEX IDX_ID_EXPORTACOES ON EXPORTACOES(ID_EXPORTACAO)
GO


IF EXISTS (SELECT * FROM SYS.objects WHERE NAME = 'ITENSEXPORTACAO' AND type ='U')
	BEGIN
		DROP TABLE ITENSEXPORTACAO
	END
GO

CREATE TABLE ITENSEXPORTACAO(
ID_ITEM			INTEGER IDENTITY (1,1) PRIMARY KEY,
ID_EXPORTACAO	INTEGER FOREIGN KEY REFERENCES EXPORTACOES(ID_EXPORTACAO),
ID_PRODUTO		INTEGER FOREIGN KEY REFERENCES PRODUTOS(ID_PRODUTO),
QUANTIDADE		INTEGER)
GO

CREATE INDEX IDX_ID_ITENSEXPORTACAO ON ITENSEXPORTACAO(ID_ITEM)
GO

IF EXISTS (SELECT * FROM SYS.objects WHERE NAME = 'IMPORTACOES' AND TYPE = 'U')
	BEGIN
		DROP TABLE IMPORTACOES
	END
GO

CREATE TABLE IMPORTACOES(
ID_IMPORTACAO	INTEGER IDENTITY (1,1) PRIMARY KEY,
ID_CLIENTE		INTEGER FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
DATA_IMPORTACAO DATE,
PORTO_ORIGEM	VARCHAR(100),
SITUACAO		VARCHAR(20)
)
GO