-- COMANDO SELECT É UTILIZADO PARA SELECIONAR AS INFORMAÇÕES DAS TABELAS
-- PODEMOS UTILIZAR O SELECT * QUE IRÁ LISTAR TODOS OS CAMPOS
-- PODEMOS UTILIZAR O SELECT * NOME_CAMPO QUE IRÁ LISTAR SOMENTE OS CAMPOS ESPECIFICOS

SELECT * FROM CLIENTES; -- * QUE IRÁ LISTAR TODOS OS CAMPOS

SELECT NOME FROM CLIENTES; -- SELECT NOME_CAMPO QUE IRÁ LISTAR SOMENTE OS CAMPOS ESPECIFICOS

SELECT NOME, CNPJ_CPF FROM CLIENTES -- SELECT MAIS DE UM NOME_CAMPO QUE IRÁ LISTAR MAIS DE UM CAMPO ESPECIFICO

