USE SGEI;

SELECT * FROM CLIENTES;
SELECT * FROM IMPORTACOES;

INSERT INTO CLIENTES (NOME, CNPJ_CPF, PAIS) VALUES ('BANTUNES LTDA','31.785.457.0001/47','BRASIL'); --ADD

DELETE FROM CLIENTES WHERE NOME = 'BANTUNES LTDA'; -- DEL 


-- DELETE EXCLUI A LINHA INTEIRA. SE QUISER MUDAR ALGO DEVE SER PELO UPDATE
-- SE HOUVER VINCULAÇÃO DO ID EM OUTRA PLANILHA NÃO PERMITIRÁ A EXCLUSÃO
